name: CI/CD 7solution-app

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*.*.*'   

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set image tag
      id: vars
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF}" == refs/heads/dev ]]; then
          echo "TAG=dev-${GITHUB_SHA::7}" >> $GITHUB_ENV
        else
          echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
        fi

    - name: Build Docker image
      run: |
        docker build -t peerasilp/7solution-app:${TAG} ./app

    - name: Push Docker image
      run: |
        docker push peerasilp/7solution-app:${TAG}
